#! /bin/sh 
for f in "$1"/*; do
  if [ -f "$f" ]; then
    SIZE="$(du -sh "${f}" | cut -f1)"
    SIZE1="$(wc -w "${f}" | cut -d ' ' -f1)"
    echo "Processing $f file..."
    echo "$SIZE"
    echo "$SIZE1"
  fi
done

